# Generated by Django 4.0.4 on 2022-06-05 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggerhouse_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_level', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=40)),
                ('birthday', models.DateField(default=datetime.datetime(2022, 6, 5, 12, 20, 7, 167143))),
                ('country', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_autor', models.EmailField(max_length=40)),
                ('topic', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dt_creation', models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 20, 7, 180141))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('alias', models.CharField(max_length=40)),
                ('rol', models.CharField(default='BLOGGER_BASIC', max_length=40)),
                ('fail_connection_attemps', models.IntegerField(default=0)),
                ('blocked', models.BooleanField(default=True)),
                ('dt_last_connection', models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 20, 7, 167143))),
                ('dt_creation', models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 20, 7, 167143))),
                ('bloggerhouse_level', models.CharField(default='BLOGGER_NEWBIE', max_length=40)),
            ],
        ),
    ]
