# Generated by Django 4.0.4 on 2022-06-21 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_usuarios', '0002_persons_posts_users_delete_person_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 21, 6, 52, 639148)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='dt_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 6, 52, 639148)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dt_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 6, 52, 635148)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dt_last_connection',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 6, 52, 635148)),
        ),
    ]
