# Generated by Django 4.0.4 on 2022-07-02 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_usuarios', '0011_alter_persons_birthday_alter_posts_dt_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 16, 58, 47, 362558)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='dt_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 58, 47, 362558)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dt_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 58, 47, 362558)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dt_last_connection',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 58, 47, 362558)),
        ),
    ]
